### ISSUE TITLE
ATListbox ShowHorzScrollbar

### ISSUE THREAD

**Issue by Alexey-T** [Alexey-T/ATButtons#40]
@srd-software Stan, I just added code for horz scrollbar-- it is

- ShowHorzScrollbar
- ScrollHorz is scroll position
- works for both ThemedScrollbars and not themed
- OnCalcScrollWidth for virtual mode (virtual is property)

need to check does it compile on Delphi? i am on Linux, lazy to reboot.

**Comment by Alexey-T** [comment]
Checked on Delphi. OS bars don't work. strange.

I changed your code of InvalidateSB to this
```
procedure TATListbox.Invalidate;
var
  R: TRect;
begin
  {$ifdef FPC}
  inherited Invalidate;
  {$else}
  // https://github.com/Alexey-T/ATFlatControls/issues/32
  if Assigned(FScrollbar) and FScrollbar.Visible then
  begin
    R:= Rect(0, 0, ClientWidth, ClientHeight);
    InvalidateRect(Handle, R, false);
  end
  else
    inherited Invalidate;
  {$endif}
end;
```

**Comment by Alexey-T** [comment]
OS bars now work okay.

**Comment by srd-software** [comment]
I looked at the invalidate change and it seems OK. However, in looking at that I found I am having trouble with scrollbars and visibility. It's not due to the Invalidate code. I'm having problems with this line in **UpdateScrollbar**:

`FScrollbar.Visible:= FThemedScrollbar;`

I prefer scrollbar visibility (themed or OS) to be based on need, i.e., are there more items in the listbox than can be displayed. So in UpdateScrollbar, I've made these changes to help get things to work:
```
//Themed:
FScrollbar.Visible:= FThemedScrollbar and  ( (ItemCount * ItemHeight) > ClientHeight );
...  
//OS:
ShowScrollBar(Handle, SB_VERT, ( (ItemCount * ItemHeight) > ClientHeight )); //true);

```
I'm never sure that my code is what you'd prefer to use, but it does what I need in my app so wanted to run it by you. This may cause issues in listboxes with variable itemheights but I wasn't sure how to address that. I also did not mess with the horz SB but it would need a similar treatment.

Another related issue I've had is I can't really set listbox.Scrollbar.Visible in my code, I've had to use the code below to make it "not visible":

`ATListbox.Scrollbar.Theme.InitialSize := 0`

So, in UpdateScrollbar I added these lines if using OS scrollbars to make sure the themed SB is hidden:

```
    FScrollbar.Theme.InitialSize := 0;
    FScrollbar.Update;
```

In my app I had to add that stuff as the themed scrollbar would never "go away" by just toggling the ThemedScrollbar property. 

Stan

**Comment by Alexey-T** [comment]
Stdctrls have type
```
  TScrollStyle = (ssNone, ssHorizontal, ssVertical, ssBoth,
    ssAutoHorizontal, ssAutoVertical, ssAutoBoth);
```

i am doing this.

**Comment by Alexey-T** [comment]
Now try how it works. Tested it in demo with combobox with all enum choices

**Comment by srd-software** [comment]
OK, logic was great but Delphi needed a few changes (see latest pull req). There is no OnDoResize in the base class so I added a WMSIZE handler. In the UpdateScrollbars, delphi doesn't have ssAutoHorizontal or ssAutoBoth, so I had to work around those. In delphi, it's either vert or horz or none. If vert or horz we assume auto is needed.

Anyway, take a look at it. It works now. I also had some code in my app causing trouble (it was old code handling the show/hide of scrollbars based on number of items, so it was conflicting with your newer stuff.

**Comment by Alexey-T** [comment]
hmm, I did another trick. 
```
  TATListboxScrollStyle = (
    alssNone,
    alssHorizontal,
    alssVertical,
    alssBoth,
    alssAutoHorizontal,
    alssAutoVertical,
    alssAutoBoth
    );
```

**Comment by srd-software** [comment]
Yes, I was wondering about doing something like that too. Is it in there now? If so I want to test it out...

**Comment by Alexey-T** [comment]
It is in git

**Comment by srd-software** [comment]
Yeah, much slicker and better code. Tightened it all up in the UpdateScrollbars proc. Much better, thanks. This was a very helpful update. I was having a devil of a time dealing with it in my app code!

**Comment by Alexey-T** [comment]
Btw, did you need combo box ? It is already in atsynedit repo.

**Comment by srd-software** [comment]
Yes, I'm using one based on the OS and it's a pain to try and "theme". Any chance that could be placed in flat controls?

**Comment by Alexey-T** [comment]
https://wiki.freepascal.org/ATSynEdit

Ops it is Lazarus only...

**Comment by srd-software** [comment]
I'll look at that and see if I could extract it.

**Comment by Alexey-T** [comment]
You cannot do this - porting to Delphi is hard here

**Comment by srd-software** [comment]
Yep, I think you are correct!
