### ISSUE TITLE
Sorry, but error again ...

### ISSUE THREAD

**Issue by hosekb** [Alexey-T/ATButtons#61]
Checking project dependencies...
Building ATFlatControlsPackage.dproj (Debug, Win32)
[dcc32 Hint] atbuttons.pas(560): H2443 Inline function 'CanvasLine' has not been expanded because unit 'System.UITypes' is not specified in USES list
[dcc32 Hint] atbuttons.pas(570): H2443 Inline function 'CanvasLine' has not been expanded because unit 'System.UITypes' is not specified in USES list
[dcc32 Hint] atbuttons.pas(654): H2443 Inline function 'CanvasPaintTriangleDown' has not been expanded because unit 'System.UITypes' is not specified in USES list
[dcc32 Hint] atbuttons.pas(656): H2443 Inline function 'CanvasPaintTriangleLeft' has not been expanded because unit 'System.UITypes' is not specified in USES list
[dcc32 Hint] atbuttons.pas(658): H2443 Inline function 'CanvasPaintTriangleRight' has not been expanded because unit 'System.UITypes' is not specified in USES list
[dcc32 Error] atflatcontrols_separator.pas(32): E2252 Method 'GetItemStr' with identical parameters already exists
[dcc32 Error] atflatcontrols_separator.pas(74): E2004 Identifier redeclared: 'TATStringSeparator.GetItemStr'
[dcc32 Error] atflatcontrols_separator.pas(77): E2251 Ambiguous overloaded call to 'GetItemStr'
  atflatcontrols_separator.pas(31): Related method: function TATStringSeparator.GetItemStr(out string): Boolean;
  atflatcontrols_separator.pas(32): Related method: function TATStringSeparator.GetItemStr(out string): Boolean;
[dcc32 Error] atflatcontrols_separator.pas(85): E2251 Ambiguous overloaded call to 'GetItemStr'
  atflatcontrols_separator.pas(31): Related method: function TATStringSeparator.GetItemStr(out string): Boolean;
  atflatcontrols_separator.pas(32): Related method: function TATStringSeparator.GetItemStr(out string): Boolean;
[dcc32 Error] atflatcontrols_separator.pas(96): E2251 Ambiguous overloaded call to 'GetItemStr'
  atflatcontrols_separator.pas(31): Related method: function TATStringSeparator.GetItemStr(out string): Boolean;
  atflatcontrols_separator.pas(32): Related method: function TATStringSeparator.GetItemStr(out string): Boolean;
[dcc32 Error] atflatcontrols_separator.pas(113): E2251 Ambiguous overloaded call to 'GetItemStr'
  atflatcontrols_separator.pas(31): Related method: function TATStringSeparator.GetItemStr(out string): Boolean;
  atflatcontrols_separator.pas(32): Related method: function TATStringSeparator.GetItemStr(out string): Boolean;
[dcc32 Error] atflatcontrols_separator.pas(124): E2251 Ambiguous overloaded call to 'GetItemStr'
  atflatcontrols_separator.pas(31): Related method: function TATStringSeparator.GetItemStr(out string): Boolean;
  atflatcontrols_separator.pas(32): Related method: function TATStringSeparator.GetItemStr(out string): Boolean;
[dcc32 Error] atflatcontrols_separator.pas(126): E2003 Undeclared identifier: 'StrToDWordDef'
[dcc32 Error] atflatcontrols_separator.pas(32): E2065 Unsatisfied forward or external declaration: 'TATStringSeparator.GetItemStr'
[dcc32 Fatal Error] attabs.pas(38): F2063 Could not compile used unit 'ATFlatControls_Separator.pas'
Failed
Elapsed time: 00:00:01.0

**Comment by Alexey-T** [comment]
@hosekb @srd-software Could you give the fix, ie patch, please?

**Comment by srd-software** [comment]
Keep in mind that I'm using Delphi 10.3 update 1 (older version)

Here's what I'm getting:
Checking project dependencies...
Compiling ATFlatControlsPackage.dproj (Debug, Win32)
brcc32 command line for "ATFlatControlsPackageResource.rc"
...
[dcc32 Hint] atbuttons.pas(560): H2443 Inline function 'CanvasLine' has not been expanded because unit 'System.UITypes' is not specified in USES list... I get a number of these but they are not the problem (hints only) ... This could be fixed with a conditional in the Uses section. Conditional would probably have to account for the delphi version being used as well. I usually just ignore these.

The 2 big problems (see log below) are the ambiguous overloads, and undeclared identifier: 'StrToDWordDef'. StrToDWordDef does not exist in delphi, looks like a lazarus-only thing. I'm not even sure what that call does but I would guess it can be written and added for delphi in a conditional.

The overload errors may be due to trying to call (for instance) GetItemStr inside GetItemInt. I'd guess the compiler can't tell which GetItemStr you want when called from inside GetItemInt. You might be better off not doing overloads but renaming the various functions with discreet function names. I'm not sure, the version of atflatcontrols I've been using for some time now doesn't even have ATFlatControls_Separator.pas in it.

Wish I could be more help!

-Stan

[dcc32 Error] atflatcontrols_separator.pas(32): E2252 Method 'GetItemStr' with identical parameters already exists
[dcc32 Error] atflatcontrols_separator.pas(74): E2004 Identifier redeclared: 'TATStringSeparator.GetItemStr'
[dcc32 Error] atflatcontrols_separator.pas(77): E2251 Ambiguous overloaded call to 'GetItemStr'
  atflatcontrols_separator.pas(31): Related method: function TATStringSeparator.GetItemStr(out string): Boolean;
  atflatcontrols_separator.pas(32): Related method: function TATStringSeparator.GetItemStr(out string): Boolean;
[dcc32 Error] atflatcontrols_separator.pas(85): E2251 Ambiguous overloaded call to 'GetItemStr'
  atflatcontrols_separator.pas(31): Related method: function TATStringSeparator.GetItemStr(out string): Boolean;
  atflatcontrols_separator.pas(32): Related method: function TATStringSeparator.GetItemStr(out string): Boolean;
[dcc32 Error] atflatcontrols_separator.pas(96): E2251 Ambiguous overloaded call to 'GetItemStr'
  atflatcontrols_separator.pas(31): Related method: function TATStringSeparator.GetItemStr(out string): Boolean;
  atflatcontrols_separator.pas(32): Related method: function TATStringSeparator.GetItemStr(out string): Boolean;
[dcc32 Error] atflatcontrols_separator.pas(113): E2251 Ambiguous overloaded call to 'GetItemStr'
  atflatcontrols_separator.pas(31): Related method: function TATStringSeparator.GetItemStr(out string): Boolean;
  atflatcontrols_separator.pas(32): Related method: function TATStringSeparator.GetItemStr(out string): Boolean;
[dcc32 Error] atflatcontrols_separator.pas(124): E2251 Ambiguous overloaded call to 'GetItemStr'
  atflatcontrols_separator.pas(31): Related method: function TATStringSeparator.GetItemStr(out string): Boolean;
  atflatcontrols_separator.pas(32): Related method: function TATStringSeparator.GetItemStr(out string): Boolean;
[dcc32 Error] atflatcontrols_separator.pas(126): E2003 Undeclared identifier: 'StrToDWordDef'
[dcc32 Error] atflatcontrols_separator.pas(32): E2065 Unsatisfied forward or external declaration: 'TATStringSeparator.GetItemStr'
[dcc32 Fatal Error] attabs.pas(38): F2063 Could not compile used unit 'ATFlatControls_Separator.pas'
Failed
Elapsed time: 00:00:09.5

**Comment by Alexey-T** [comment]
thanks again. I made fixes from your report, try again?

**Comment by srd-software** [comment]
Still getting ambiguous errors (see copy of log below). 

I think what you might need to do is to change the first GetItemStr from:
```function GetItemStr(out AValue: string): boolean; overload;```
to:
```function GetItemStr(out AValue: string; dummy:string): boolean; overload;```

Then, when you call it, to get that first version of it you'd do:
```Result:= GetItemStr(SVal,'');```

I tried that and it worked when I changed the various calls from GetItemStr(SVal) to GetItemStr(SVal,'') in the code. Once it was working there however, I got an error in attabs.pas where it was called there, so you'd also have to use GetItemStr(SVal,'') to get the first version (and of course anywhere else it's called as GetItemStr(SVal) ).

I'm sure there is a more efficient and elegant way to do all that but that seems to be the problem. Each overload needs a different set of params in it. Apparently the compiler is confused with GetItemStr(out AValue: string) since all the GetItemStr overloads start out with that.

-Stan

 (Debug, Win32)
...
  -NOC:\Users\Public\Documents\Embarcadero\Studio\20.0\Dcp  ATFlatControlsPackage.dpk   
[dcc32 Error] atflatcontrols_separator.pas(32): E2252 Method 'GetItemStr' with identical parameters already exists
[dcc32 Error] atflatcontrols_separator.pas(74): E2004 Identifier redeclared: 'TATStringSeparator.GetItemStr'
[dcc32 Error] atflatcontrols_separator.pas(77): E2251 Ambiguous overloaded call to 'GetItemStr'
  atflatcontrols_separator.pas(31): Related method: function TATStringSeparator.GetItemStr(out string): Boolean;
  atflatcontrols_separator.pas(32): Related method: function TATStringSeparator.GetItemStr(out string): Boolean;
[dcc32 Error] atflatcontrols_separator.pas(85): E2251 Ambiguous overloaded call to 'GetItemStr'
  atflatcontrols_separator.pas(31): Related method: function TATStringSeparator.GetItemStr(out string): Boolean;
  atflatcontrols_separator.pas(32): Related method: function TATStringSeparator.GetItemStr(out string): Boolean;
[dcc32 Error] atflatcontrols_separator.pas(96): E2251 Ambiguous overloaded call to 'GetItemStr'
  atflatcontrols_separator.pas(31): Related method: function TATStringSeparator.GetItemStr(out string): Boolean;
  atflatcontrols_separator.pas(32): Related method: function TATStringSeparator.GetItemStr(out string): Boolean;
[dcc32 Error] atflatcontrols_separator.pas(32): E2065 Unsatisfied forward or external declaration: 'TATStringSeparator.GetItemStr'
[dcc32 Fatal Error] attabs.pas(38): F2063 Could not compile used unit 'ATFlatControls_Separator.pas'
Failed
Elapsed time: 00:00:01.6

**Comment by Alexey-T** [comment]
made new fix. pls try it?
error - due to GetItemStr(out s: string) + GetItemStr(out s: UnicodeString)---- same in delphi.

**Comment by Alexey-T** [comment]
I hope ATTabs still work in delphi?

**Comment by srd-software** [comment]
> made new fix. pls try it?
> error - due to GetItemStr(out s: string) + GetItemStr(out s: UnicodeString)---- same in delphi.

OK, the GetItemStr errors are gone but now getting this:
[dcc32 Warning] attabs.pas(3098): W1036 Variable 'bSwitchTab' might not have been initialized
[dcc32 Hint] atflattoolbar.pas(254): H2077 Value assigned to 'CtlSource' never used
[dcc32 Hint] atflattoolbar.pas(261): H2077 Value assigned to 'akind2' never used
[dcc32 Hint] atflattoolbar.pas(260): H2077 Value assigned to 'akind' never used
[dcc32 Hint] atflattoolbar.pas(266): H2077 Value assigned to 'akind2' never used
[dcc32 Hint] atflattoolbar.pas(265): H2077 Value assigned to 'akind' never used
[dcc32 Error] atflattoolbar.pas(354): E2035 Not enough actual parameters
[dcc32 Hint] atflattoolbar.pas(31): H2219 Private symbol 'PopupForDropdownClick' declared but never used
[dcc32 Hint] atflattoolbar.pas(33): H2219 Private symbol 'SetButtonWidth' declared but never used
[dcc32 Fatal Error] atflatcontrols_register.pas(13): F2063 Could not compile used unit 'atflattoolbar.pas'

**Comment by srd-software** [comment]
> I hope ATTabs still work in delphi?

My earlier version has been working well. Can't test this newest version yet until it compiles but I will.

Oh, if you mean is it still in the GetIt thing, yes, it's still there.

**Comment by Alexey-T** [comment]
made more fixes, pls try.

**Comment by srd-software** [comment]
Compiles OK now. I tried a few current projects using the controls and they seem OK at me so far.

**Comment by Alexey-T** [comment]
Thanks for this help

**Comment by hosekb** [comment]
Now is all OK, thanks
Bohous

------ Původní zpráva ------
Od: "Alexey T." <notifications@github.com>
Komu: "Alexey-T/ATFlatControls" <ATFlatControls@noreply.github.com>
Kopie: "hosekb" <hosekb@gmail.com>; "Mention" 
<mention@noreply.github.com>
Odesláno: 10.02.2021 15:23:29
Předmět: Re: [Alexey-T/ATFlatControls] Sorry, but error again ... (#61)

**Comment by Alexey-T** [comment]
As 'thank you' I like to get blog post about CudaText, or a youtube video about it.

**Comment by hosekb** [comment]
Hi,
problem with Delphi 10.2

procedure DrawPlusSign(C: TCanvas; const R: TRect; ASize, ALineWidth: 
integer; AColor: TColor);
var
   CX, CY: integer;
begin
   CX:= (R.Left+R.Right) div 2;
   CY:= (R.Top+R.Bottom) div 2;
   C.Pen.Width:= ALineWidth;
   C.Pen.EndCap:= pecSquare;
   DrawLine(C, CX-ASize, CY, CX+ASize, CY, AColor);
   DrawLine(C, CX, CY-ASize, CX, CY+ASize, AColor);
   C.Pen.Width:= 1;
end;

Bohous

**Comment by Alexey-T** [comment]
@hosekb Do you get error for this line?

   C.Pen.EndCap:= pecSquare;

or where exactly?

**Comment by Alexey-T** [comment]
I made the IFDEF here, pls test again.

**Comment by hosekb** [comment]
I made also correction in atTabs:

procedure DrawPlusSign(C: TCanvas; const R: TRect; ASize, ALineWidth: 
integer; AColor: TColor);
var
   CX, CY: integer;
begin
   CX:= (R.Left+R.Right) div 2;
   CY:= (R.Top+R.Bottom) div 2;
   C.Pen.Width:= ALineWidth;
   {$ifdef FPC}
   C.Pen.EndCap:= pecSquare;
   {$endif}
   DrawLine(C, CX-ASize, CY, CX+ASize, CY, AColor);
   DrawLine(C, CX, CY-ASize, CX, CY+ASize, AColor);
   C.Pen.Width:= 1;
end;


------ Původní zpráva ------
Od: "Alexey T." ***@***.***>
Komu: "Alexey-T/ATFlatControls" ***@***.***>
Kopie: "hosekb" ***@***.***>; "Mention" 
***@***.***>
Odesláno: 11.11.2021 11:50:07
Předmět: Re: [Alexey-T/ATFlatControls] Sorry, but error again ... (#61)

**Comment by Alexey-T** [comment]
Ok, i did this change too.
